@component('components.form.form-modal')
    @slot('Method', $Method ?? 'GET')
    @slot('Titulo', $Titulo ?? '')
    @slot('Route', $Route ?? '#')
    @slot('IsUpload', $IsUpload ?? false)
    @slot('IsNew', $IsNew ?? false)
    @slot('IsModal', $IsModal ?? false )
    @slot('items_forms', $items_forms ?? '')
    @slot('item', $items ?? null)
    @slot('formData', 'formFullModal')
    @slot('user',$user ?? null)
    @slot('denuncia_id',$denuncia_id ?? null)
    @slot('respuesta_id',$respuesta_id ?? null)
@endcomponent
