@component('components.form.form-modal')
    @slot('Method', "POST" ?? 'GET')
    @slot('Titulo', "Comentarios del folio: ".$id ?? '')
    @slot('Route', "saveRespuestaMobileDen" ?? '#')
    @slot('IsUpload', $IsUpload ?? false)
    @slot('IsNew', true ?? false)
    @slot('IsModal', true ?? false )
    @slot('items_forms', "SIAC.denuncia.respuesta.__respuesta.__respuestamobile_list" ?? '')
    @slot('item', $items ?? null)
    @slot('formData', 'formFullModal')
    @slot('user',$user ?? null)
    @slot('id',$id ?? null)
    @slot('denunciamobile_id',$denunciamobile_id ?? null)
@endcomponent
