@component('components.form.form-modal')
    @slot('Method', $Method ?? 'GET')
    @slot('Titulo', $Titulo ?? 'Nuevo')
    @slot('Route', $Route ?? '#')
    @slot('IsUpload', $IsUpload ?? false)
    @slot('IsNew', $IsNew ?? false)
    @slot('calles', $calles ?? null)
    @slot('colonias', $colonias ?? null)
    @slot('comunidades', $comunidades ?? null)
    @slot('codigospostales', $codigospostales ?? null)
    @slot('items_forms', $items_forms ?? '')
    @slot('formData', 'formFullModal')
    @slot('user',$user ?? null)
@endcomponent
