@component('components.form.form-modal')
    @slot('Method', $Method ?? 'GET')
    @slot('Titulo', $Titulo ?? '')
    @slot('Route', $Route ?? '#')
    @slot('IsUpload', $IsUpload ?? false)
    @slot('IsNew', $IsNew ?? false)
    @slot('IsModal', $IsModal ?? false )
    @slot('items_forms', $items_forms ?? '')
    @slot('items', $items ?? null)
    @slot('formData', 'formFullModal')
    @slot('user',$user ?? null)
    @slot('delegados',$delegados ?? null)
    @slot('tipocomunidades',$tipocomunidades ?? null)
    @slot('ciudades',$ciudades ?? null)
    @slot('municipios',$municipios ?? null)
    @slot('estados',$estados ?? null)
    @slot('ciudad_id',$ciudad_id ?? null)
    @slot('municipio_id',$municipio_id ?? null)
    @slot('estado_id',$estado_id ?? null)
@endcomponent
